version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
      - ./environments/ruby.env
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    tty: true
    command: zsh -c "bundle exec rails db:migrate && rails s"

  front:
    build:
      context: ./frontend
    dockerfile: Dockerfile-prod
    environment:
      - CHOKIDAR_USEPOLLING=true
      - IS_REACT_ACT_ENVIRONMENT=true
      - FAST_REFRESH=false
      - NODE_OPTIONS=--max_old_space_size=1024
      - node_modules-prod-data:/frontend/node_modules
    volumes:
      - build-prod-data:/frontend/build
    command: zsh -c "yarn install && yarn build && npx serve -s build -n"
    tty: true
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx
    environment:
      - HOST=short-diary.com
    volumes:
      - public-prod-data:/Short-Diary/public
      - build-prod-data:/Short-Diary/frontend/build
      - tmp-prod-data:/Short-Diary/tmp
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  node_modules-prod-data:
  build-prod-data:
  public-prod-data:
  tmp-prod-data:
