version: '3'

services:
  api:
    image:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    tty: true
    ports:
      - 3000:3000
    command: zsh -c 'bundle exec pumactl start'

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    ports:
      - 5000:5000
    tty: true
    command: zsh -c 'yarn install && npx serve -s build'
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  public-prod-data:
  tmp-prod-data: