version: '3'
x-aws-vpc: 'vpc-123456'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file:
      - ./environments/ruby.env
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    tty: true
    ports:
      - 3000:3000
    command: zsh -c 'bundle exec pumactl start'

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    volumes:
      - node_modules-prod-data:/frontend/node_modules
    ports:
      - 5000:5000
    tty: true
    command: zsh -c 'yarn install && yarn build && npx serve -s build'
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  public-prod-data:
  tmp-prod-data:
  node_modules-prod-data: