version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        UID: 1000
        GID: 1000
    env_file:
      - ./environments/ruby.env
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    tty: true
    command: zsh -c "bundle exec rails db:migrate && rails s"

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    tty: true
    volumes:
      - build-prod-data:/frontend/build
      - node_modules-prod-data:/frontend/node_modules
    command: zsh -c "yarn install && yarn build && npx serve -s build -n"
    depends_on:
      - api
    environment:
      - NODE_OPTIONS=--max_old_space_size=1024

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    volumes:
      - public-prod-data:/Short-Diary/public
      - build-prod-data:/Short-Diary/frontend/build
      - tmp-prod-data:/Short-Diary/tmp
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  node_modules-prod-data:
  build-prod-data:
  public-prod-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./public
    name: public-data
  tmp-prod-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./tmp
    name: tmp-data
