version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    tty: true
    command: zsh -c 'bundle exec pumactl start'

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    tty: true
    volumes:
      - build-prod-data:/frontend/build
    command: zsh -c 'npx serve -s build -n'
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx
    volumes:
      - public-prod-data:/Short-Diary/public
      - build-prod-data:/Short-Diary/frontend/build
      - tmp-prod-data:/Short-Diary/tmp
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  public-prod-data:
  tmp-prod-data:
  build-prod-data: