version: '3'
services:
  db:
    image: mysql:8.0.22
    env_file:
      - ./environments/db_prod.env
    volumes:
      - db-prod-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
    env_file:
      - ./environments/db_prod.env
      - ./environments/ruby.env
      - ./environments/rails.env
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
      - log-prod-data:/Short-Diary/log
    tty: true
    command: zsh -c "bundle exec pumactl start"
    depends_on:
      - db

  front:
    build:
      context: ./frontend
    volumes:
      - node_modules-prod-data:/frontend/node_modules
    ports:
      - 3000:3000
    tty: true
    command: zsh -c "yarn install && npx serve -s build -p 3000"
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx
    volumes:
      - public-prod-data:/Short-Diary/public
      - tmp-prod-data:/Short-Diary/tmp
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  db-prod-data:
  public-prod-data:
  tmp-prod-data:
  log-prod-data:
  node_modules-prod-data: