version: "3.8"
services:
  db:
    image: mysql:8.0.22
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
    env_file:
      - ./environments/db.env
      - ./environments/ruby.env
    volumes:
      - .:/Short-Diary
      - public-data:/Short-Diary/public
      - tmp-data:/Short-Diary/tmp
      - storage-data:/Short-Diary/storage
    ports:
      - 3001:3001
    tty: true
    command: zsh -c "bundle exec pumactl start"
    depends_on:
      - db

  front:
    build:
      context: ./frontend
    environment:
      - IS_REACT_ACT_ENVIRONMENT=true
      - FAST_REFRESH=false
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    tty: true
    user: "1000:1000"
    command: zsh -c 'yarn install --frozen-lockfile && /bin/zsh'
    depends_on:
      - api

  nginx:
    build:
      context: ./nginx
    volumes:
      - public-data:/Short-Diary/public
      - tmp-data:/Short-Diary/tmp
    environment:
      - HOST=localhost
    ports:
      - 80:80
    depends_on:
      - api
      - front

volumes:
  db-data:
  public-data:
  tmp-data:
  storage-data:
