default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: Short_Diary_development

test:
  <<: *default
  database: Short_Diary_test

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production_db, :db_name) %>
  password: <%= Rails.application.credentials.dig(:production_db, :password) %>
  username: <%= Rails.application.credentials.dig(:production_db, :user_name) %>
  host: <%= Rails.application.credentials.dig(:production_db, :host) %>
