default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: Short_Diary_development

test:
  <<: *default
  database: Short_Diary_test

production:
  <<: *default
  database: Short_Diary_production
  username: Short_Diary
  password: <%= ENV['SHORT_DIARY_DATABASE_PASSWORD'] %>
