export const REQUEST_STATE: {
  INITIAL: "INITIAL";
  LOADING: "LOADING";
  OK: "OK";
} = {
  INITIAL: "INITIAL",
  LOADING: "LOADING",
  OK: "OK",
};

export const HTTP_STATUS_CODE: {
  UNAUTHORIZED: 401;
  FORBIDDEN: 403;
  UNPROCESSABLE: 422;
} = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  UNPROCESSABLE: 422,
};
